{% set version = "0.1.2" %}
{% set name = "xrviz" %}
{% set sha256 = "6cacd49776804663a772128ae2caa261499dd5b297676e6e5f02258737fe4ef4" %}

package:
   name:  {{ name }}
   version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - jinja2
  run:
    - python >=3.6
    - xarray
    - cartopy
    - panel >=0.5.1
    - holoviews ==1.12.1
    - hvplot
    - netcdf4
    - datashader
    - metpy

test:
  imports:
    - xrviz

about:
  home: https://github.com/intake/xrviz
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Interactive visualisation interface for Xarrays"

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs
    - hdsingh
