{% set name = "xrviz" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xrviz-{{ version }}.tar.gz
  sha256: 65deb63b695f4edcfa5d4eb85319c0f48ac43e2fbc796f7b8fd3e52be2261206

build:
  number: 2
  noarch: python
  entry_points:
    - xrviz = xrviz.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - datashader
    - holoviews
    - hvplot
    - netcdf4
    - panel >=0.7.0
    - python >=3.6
    - xarray >=0.14.1

test:
  imports:
    - xrviz
    - xrviz.sample_data
  commands:
    - pip check
    - xrviz --help
  requires:
    - pip

about:
  home: https://pypi.org/project/xrviz/
  summary: Interactive visualisations for xarrays
  license: BSD-Protection
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs
    - hdsingh
