{% set version = "0.1.4" %}

package:
   name:  xrviz
   version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xrviz/xrviz-{{ version }}.tar.gz
  sha256: 65deb63b695f4edcfa5d4eb85319c0f48ac43e2fbc796f7b8fd3e52be2261206

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - jinja2
  run:
    - python >=3.6
    - xarray >=0.14.1
    - cartopy
    - panel >=0.7.0
    - holoviews
    - hvplot
    - netcdf4
    - datashader
    - metpy

test:
  imports:
    - xrviz

about:
  home: https://github.com/intake/xrviz
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Interactive visualisation interface for Xarrays"

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs
    - hdsingh
